[profile.release]
# To simplify panic handling, don't unwind the stack, just crash
panic = "abort"

[build]
# compile for our RV32IM processor
target = "riscv32im-unknown-none-elf"

[target.riscv32im-unknown-none-elf]
# specify a linker script
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-Tsmallmemory.x"
]
